#!/usr/bin/env python3
"""Turn a BDF bitmap font into a C++ header with the printable ASCII glyphs.

The generated data is checked in, so the build needs neither this script nor the
font file. Keeping the generator around is what makes the numbers in that header
verifiable instead of magic.

Usage:
    tools/bdf_to_header.py external/rpi-rgb-led-matrix/fonts/5x7.bdf \\
        > src/gfx/font5x7_data.h

The fonts shipped with rpi-rgb-led-matrix are public domain, except
tom-thumb.bdf; see external/rpi-rgb-led-matrix/fonts/README.md.
"""

import sys

FIRST_CHAR = 32  # space
LAST_CHAR = 126  # tilde


def parse_bdf(path):
    """Returns {encoding: {'bbx': (w, h, xoff, yoff), 'rows': [int, ...]}}."""
    glyphs = {}
    encoding = None
    bbx = None
    rows = None

    with open(path, encoding="latin-1") as handle:
        for line in handle:
            line = line.strip()
            if line.startswith("ENCODING "):
                encoding = int(line.split()[1])
            elif line.startswith("BBX "):
                bbx = tuple(int(v) for v in line.split()[1:5])
            elif line == "BITMAP":
                rows = []
            elif line == "ENDCHAR":
                if encoding is not None and rows is not None:
                    glyphs[encoding] = {"bbx": bbx, "rows": rows}
                encoding, bbx, rows = None, None, None
            elif rows is not None and line:
                rows.append(int(line, 16))

    return glyphs


def main():
    if len(sys.argv) != 2:
        sys.exit(f"usage: {sys.argv[0]} <font.bdf>")

    path = sys.argv[1]
    glyphs = parse_bdf(path)

    # Every glyph we care about must share one box, otherwise a fixed-width
    # renderer would misplace them and we would need per-glyph offsets.
    boxes = {glyphs[c]["bbx"] for c in range(FIRST_CHAR, LAST_CHAR + 1) if c in glyphs}
    if len(boxes) != 1:
        sys.exit(f"expected a single bounding box, found {boxes}")

    width, height, _, _ = boxes.pop()

    print("// Generated by tools/bdf_to_header.py — do not edit by hand.")
    print(f"// Source: {path} (public domain, see that project's fonts/README.md)")
    print("//")
    print("// One byte per glyph row. Bit 0 is the leftmost pixel, so a row reads")
    print("// left to right from the low bit upwards.")
    print()
    print("#pragma once")
    print()
    print("#include <cstdint>")
    print()
    print("namespace matrixos::font5x7")
    print("{")
    print()
    print(f"inline constexpr int kWidth = {width};")
    print(f"inline constexpr int kHeight = {height};")
    print(f"inline constexpr char kFirstChar = {FIRST_CHAR};")
    print(f"inline constexpr char kLastChar = {LAST_CHAR};")
    print()
    print(f"inline constexpr std::uint8_t kGlyphs[{LAST_CHAR - FIRST_CHAR + 1}][{height}] = {{")

    for code in range(FIRST_CHAR, LAST_CHAR + 1):
        glyph = glyphs.get(code)
        rows = glyph["rows"] if glyph else [0] * height

        converted = []
        for row in rows:
            # BDF packs each row into bytes with the leftmost pixel in the high
            # bit. Reverse it so bit 0 is the leftmost pixel, which makes the
            # renderer a plain shift-and-test.
            bits = 0
            for column in range(width):
                if row & (0x80 >> column):
                    bits |= 1 << column
            converted.append(bits)

        label = chr(code) if code != 32 else "space"
        if label == "\\":
            label = "backslash"
        values = ", ".join(f"0x{value:02X}" for value in converted)
        print(f"    {{{values}}}, // {code:3d}  {label}")

    print("};")
    print()
    print("} // namespace matrixos::font5x7")


if __name__ == "__main__":
    main()
